### PR TITLE
test commit

### PR DESCRIPTION
**Pull request by Spiral-Memory**
# Brief Title

## Acceptance Criteria fulfillment

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Fixes # (issue)

## PR-Preview:

https://devanshkansagra.github.io/EC/pulls/<pr-number>

### CODE REVIEW

**Review by devanshkansagra — APPROVED** [review]

**Review by devanshkansagra — APPROVED** [review]

**Review by devanshkansagra — APPROVED** [review]

**Review by devanshkansagra — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Hey      before this give it name, that maybe causing issue(not sure) - uses: marocchino/sticky-pull-request-comment@v2

**Comment by devanshkansagra** [comment]
no no There is issue in removing script

**Comment by Spiral-Memory** [comment]
> no no There is issue in removing script

Cleanup might be failing bcoz you are not checking out repo

**Comment by devanshkansagra** [comment]
now I have added

**Comment by Spiral-Memory** [comment]
Closure worked.. now only comments issue is there in both closure and live deployment

**Pull request closed without merging**
