### PR TITLE
added a few change in all monorepo

### PR DESCRIPTION
**Pull request by Spiral-Memory**
# Brief Title

## Acceptance Criteria fulfillment

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Fixes # (issue)

## PR-Preview:

https://devanshkansagra.github.io/EC/pulls/<pr-number>

### CODE REVIEW

**Review by devanshkansagra — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
@devanshkansagra 

This won't be able to delete pr-preview

**Comment by Spiral-Memory** [comment]
@devanshkansagra approve krna bhai

**Review by devanshkansagra — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
@devanshkansagra 
If a PR is raised by someone else, it is unable to find pr number and hence not commenting, access pr number correctly, don't use array:

image

**Review by devanshkansagra — APPROVED** [review]

**Review by devanshkansagra — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
@devanshkansagra approve

**Review by devanshkansagra — APPROVED** [review]

**Review by devanshkansagra — APPROVED** [review]

**Pull request merged**
